---
  - name: Install PHP5-FPM
    sudo: yes
    apt:  package=php5-fpm state=latest

#  - name: Change default php config
#    sudo: yes
#    template: src=php.ini dest=/etc/php5/fpm/php.ini
#    notify: restart php5-fpm